---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: recyclarr
spec:
  chartRef:
    kind: OCIRepository
    name: recyclarr
  interval: 1h
  values:
    controllers:
      recyclarr:
        annotations:
          reloader.stakater.com/auto: "true"
        strategy: Recreate
        containers:
          app:
            nameOverride: "{{ .Release.Name }}"
            image:
              repository: ghcr.io/recyclarr/recyclarr
              tag: 8.7.2@sha256:6e69e009e1cd7493ff6093e8e187b5d3788c75b4a2c0c5127b6a1beda1c19728
            env:
              CRON_SCHEDULE: "@daily"
              RECYCLARR_CREATE_CONFIG: "true"
              TZ: Australia/Melbourne
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 128Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        globalMounts:
          - path: /config
      configs-dir:
        type: emptyDir
        globalMounts:
          - path: /config/configs
      configs:
        type: configMap
        name: recyclarr-configs
        advancedMounts:
          recyclarr:
            app:
              - path: /config/configs/radarr-4k.yaml
                subPath: radarr-4k.yaml
                readOnly: true
              - path: /config/configs/radarr-anime.yaml
                subPath: radarr-anime.yaml
                readOnly: true
              - path: /config/configs/radarr.yaml
                subPath: radarr.yaml
                readOnly: true
              - path: /config/configs/sonarr-anime.yaml
                subPath: sonarr-anime.yaml
                readOnly: true
              - path: /config/configs/sonarr.yaml
                subPath: sonarr.yaml
                readOnly: true
