---
# yaml-language-server: $schema=https://schemas.materia.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bazarr-anime
spec:
  components:
    - ../../../../components/authentik-forward-auth
    - ../../../../components/kopiur/backup
    - ../../../../components/theme-park
    - ../../../../components/zeroscaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/media/arr-apps/bazarr-anime
  postBuild:
    substitute:
      APP: *app
      THEME_PARK_APP: bazarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
---
# yaml-language-server: $schema=https://schemas.materia.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app bazarr
spec:
  components:
    - ../../../../components/authentik-forward-auth
    - ../../../../components/kopiur/backup
    - ../../../../components/theme-park
    - ../../../../components/zeroscaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/media/arr-apps/bazarr
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
# ---
# # yaml-language-server: $schema=https://schemas.materia.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &app lidarr
# spec:
#   components:
#     - ../../../../components/authentik-forward-auth
#     - ../../../../components/theme-park
#     - ../../../../components/volsync
#     - ../../../../components/zeroscaler
#   dependsOn:
#     - name: rook-ceph-cluster
#       namespace: rook-ceph
#   interval: 30m
#   path: ./kubernetes/apps/media/arr-apps/lidarr
#   postBuild:
#     substitute:
#       APP: *app
#       VOLSYNC_CAPACITY: 5Gi
#       VOLSYNC_SCHEDULE: "18 * * * *"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#     namespace: flux-system
#   targetNamespace: media
#   wait: false
---
# yaml-language-server: $schema=https://schemas.materia.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app prowlarr
spec:
  components:
    - ../../../../components/authentik-forward-auth
    - ../../../../components/kopiur/backup
    - ../../../../components/theme-park
    - ../../../../components/zeroscaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/media/arr-apps/prowlarr
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
---
# yaml-language-server: $schema=https://schemas.materia.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr
spec:
  components:
    - ../../../../components/authentik-forward-auth
    - ../../../../components/kopiur/backup
    - ../../../../components/theme-park
    - ../../../../components/zeroscaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/media/arr-apps/radarr
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
---
# yaml-language-server: $schema=https://schemas.materia.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr-anime
spec:
  components:
    - ../../../../components/authentik-forward-auth
    - ../../../../components/kopiur/backup
    - ../../../../components/theme-park
    - ../../../../components/zeroscaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/media/arr-apps/radarr-anime
  postBuild:
    substitute:
      APP: *app
      THEME_PARK_APP: radarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
---
# yaml-language-server: $schema=https://schemas.materia.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app radarr-4k
spec:
  components:
    - ../../../../components/authentik-forward-auth
    - ../../../../components/kopiur/backup
    - ../../../../components/theme-park
    - ../../../../components/zeroscaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/media/arr-apps/radarr-4k
  postBuild:
    substitute:
      APP: *app
      THEME_PARK_APP: radarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
---
# yaml-language-server: $schema=https://schemas.materia.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app recyclarr
spec:
  components:
    - ../../../../components/kopiur/backup
    - ../../../../components/zeroscaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/media/arr-apps/recyclarr
  postBuild:
    substitute:
      APP: *app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
---
# yaml-language-server: $schema=https://schemas.materia.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sonarr
spec:
  components:
    - ../../../../components/authentik-forward-auth
    - ../../../../components/kopiur/backup
    - ../../../../components/theme-park
    - ../../../../components/zeroscaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/media/arr-apps/sonarr
  postBuild:
    substitute:
      APP: *app
      KOPIUR_CAPACITY: 10Gi
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
---
# yaml-language-server: $schema=https://schemas.materia.wtf/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app sonarr-anime
spec:
  components:
    - ../../../../components/authentik-forward-auth
    - ../../../../components/kopiur/backup
    - ../../../../components/theme-park
    - ../../../../components/zeroscaler
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  interval: 30m
  path: ./kubernetes/apps/media/arr-apps/sonarr-anime
  postBuild:
    substitute:
      APP: *app
      THEME_PARK_APP: sonarr
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: media
  wait: false
