---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-system

components:
  - ../../components/alerts
  - ../../components/namespace

patches:
  - target:
      kind: Namespace
    patch: |
      - op: add
        path: /metadata/labels
        value:
          resource.kubernetes.io/admin-access: "true"

resources:
  - ./cilium/ks.yaml
  - ./coredns/ks.yaml
  - ./crd-schema-publisher/ks.yaml
  - ./drm-exporter/ks.yaml
  - ./etcd-defrag/ks.yaml
  - ./intel-gpu-resource-driver/ks.yaml
  - ./metrics-server/ks.yaml
