---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media

components:
  - ../../components/alerts
  - ../../components/kopiur/secret

resources:
  - ./namespace.yaml
  - ./arr-apps/ks.yaml
  - ./calibre-web-automated/ks.yaml
  - ./shelfmark/ks.yaml
  - ./emby/ks.yaml
  - ./flaresolverr/ks.yaml
  - ./notifiarr/ks.yaml
  - ./plex/ks.yaml
  - ./sabnzbd/ks.yaml
  - ./seerr/ks.yaml
  - ./stash/ks.yaml
