---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbitmanage
spec:
  chartRef:
    kind: OCIRepository
    name: qbitmanage
  interval: 1h
  values:
    controllers:
      qbitmanage:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            nameOverride: "{{ .Release.Name }}"
            image:
              repository: ghcr.io/stuffanthings/qbit_manage
              tag: v4.12.0@sha256:7a7db6bdec57baf06d580e97d44f00185ff3a774335951b0affc849e014cb8f8
            env:
              QBT_CONFIG: "/config/config.yaml"
              QBT_CAT_UPDATE: true
              QBT_CROSS_SEED: true
              QBT_DIVIDER: =
              QBT_DRY_RUN: false
              QBT_LOG_LEVEL: INFO
              QBT_RECHECK: true
              QBT_REM_ORPHANED: true
              QBT_REM_UNREGISTERED: true
              QBT_RUN: false
              QBT_SCHEDULE: 30
              QBT_SHARE_LIMITS: true
              QBT_SKIP_CLEANUP: false
              QBT_SKIP_QB_VERSION_CHECK: true
              QBT_TAG_NOHARDLINKS: true
              QBT_TAG_TRACKER_ERROR: true
              QBT_TAG_UPDATE: true
              QBT_WIDTH: 100
            resources:
              requests:
                cpu: 10m
                memory: 128Mi
              limits:
                memory: 1Gi
            securityContext:
              runAsNonRoot: true
              runAsUser: 1000
              runAsGroup: 1000
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            lifecycle:
              postStart:
                exec:
                  command:
                    [
                      "/bin/sh",
                      "-c",
                      "cp /secret/config.yaml /config/config.yaml",
                    ]
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: "{{ .Release.Name }}"
        advancedMounts:
          qbitmanage:
            app:
              - path: /config
      app:
        type: emptyDir
        medium: Memory
        globalMounts:
          - path: /tmp
          - path: /config/logs
      config-file:
        type: secret
        name: "{{ .Release.Name }}-secret"
        globalMounts:
          - path: /secret/config.yaml
            subPath: config.yaml
            readOnly: true
      data:
        type: nfs
        server: nas.internal
        path: /mnt/tank/data
        globalMounts:
          - path: /data
      torrents:
        type: nfs
        server: nas.internal
        path: /mnt/apps/apps-nfs/torrents/BT_backup
        globalMounts:
          - path: /torrents
