---
# yaml-language-server: $schema=https://schemas.materia.wtf/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: lwolf-charts
spec:
  interval: 1h
  url: https://charts.lwolf.org
  timeout: 3m
