---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources:
  - ./cluster.yaml
  - ./externalsecret-backup.yaml
  - ./externalsecret-credentials.yaml
  - ./objectstore.yaml
  - ./pooler.yaml
  - ./prometheusrule.yaml
  - ./pushsecret.yaml
  - ./scheduledbackup.yaml
