---
# yaml-language-server: $schema=https://schemas.materia.wtf/postgresql.cnpg.io/scheduledbackup_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-${APP}-backup
spec:
  schedule: "0 0 16 * * *"   # daily 16:00 UTC = 02:00/03:00 Melbourne
  backupOwnerReference: self
  cluster:
    name: postgres-${APP}
  method: barmanObjectStore
