---
# yaml-language-server: $schema=https://schemas.materia.wtf/source.toolkit.fluxcd.io/ocirepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: k8tz
spec:
  interval: 30m
  timeout: 60s
  url: oci://ghcr.io/home-operations/charts-mirror/k8tz
  ref:
    tag: 0.19.0
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
