node_exporter_enabled: true
smartctl_exporter_enabled: true

# renovate: datasource=github-releases depName=prometheus/node_exporter
node_exporter_version: "1.12.1"
# renovate: datasource=github-releases depName=prometheus-community/smartctl_exporter
smartctl_exporter_version: "0.15.0"
smartctl_exporter_system_user: root
smartctl_exporter_system_group: root
