---
apiVersion: discovery.k8s.io/v1
kind: EndpointSlice
metadata:
  name: internal-pikvm
  namespace: network
  labels:
    kubernetes.io/service-name: internal-pikvm
addressType: IPv4
endpoints:
  - addresses:
      - 192.168.1.22
ports:
  - port: 443
    name: https
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: internal-pikvm
  namespace: network
spec:
  type: ClusterIP
  clusterIP: None # Headless service for the EndpointSlice
  ports:
    - port: 443
      targetPort: 443
      name: https
---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: TLSRoute
metadata:
  name: external-service-tlsroute-pikvm
  namespace: network
  annotations:
    external-dns.kubernetes.io/target: "internal-tls.materia.wtf"
spec:
  parentRefs:
    - name: envoy-internal-tls
      namespace: network
      sectionName: tls
  hostnames:
    - "pikvm.materia.wtf"
  rules:
    - backendRefs:
        - name: internal-pikvm
          port: 443
